### ISSUE TITLE
Permission denied on drpall-master.h5.lock and drp_errors.txt at Utah

### ISSUE THREAD

**Issue by ajmejia** [sdss/lvmdrp#134]
while running the master branch of the DRP at Utah from the interactive node as myself, I'm getting these errors at the end of the reduction:

`Failed to reduce science frame mjd 60514 exposure 22026: [Errno 13] Permission denied: '/uufs/chpc.utah.edu/common/home/sdss50/sdsswork/lvm/spectro/redux/master/drpall-master.h5.lock'`

and

`PermissionError: [Errno 13] Permission denied: '/uufs/chpc.utah.edu/common/home/sdss50/sdsswork/lvm/spectro/redux/master/drp_errors.txt'`

This might be fixed by setting the right group permissions while creating these files for the first time.

**Comment by ndrory** [comment]
Or make sure the correct umask is set when we run the reduction scripts.

N.

— Niv Drory —
McDonald Observatory, The University of Texas at Austin
https://www.as.utexas.edu/~drory

On Aug 9, 2024, at 09:05, Alfredo Mejia-Narvaez ***@***.***> wrote:

﻿

while running the master branch of the DRP at Utah from the interactive node as myself, I'm getting these errors at the end of the reduction:

Failed to reduce science frame mjd 60514 exposure 22026: [Errno 13] Permission denied: '/uufs/chpc.utah.edu/common/home/sdss50/sdsswork/lvm/spectro/redux/master/drpall-master.h5.lock'

and

PermissionError: [Errno 13] Permission denied: '/uufs/chpc.utah.edu/common/home/sdss50/sdsswork/lvm/spectro/redux/master/drp_errors.txt'

This might be fixed by setting the right group permissions while creating these files for the first time.
