### ISSUE TITLE
Add detection (and removal) of pixel shifts to preprocessing in main pipeline

### ISSUE THREAD

**Issue by ndrory** [sdss/lvmdrp#61]
Currently, dealing with the pixel shifts is done in the scripts that generate master cals. We should be doing it to all frames and the logical place to do it is in the preprocessing steps. We also should add header keywords to mark the results of the detection and removal of the shifts.

**Comment by ajmejia** [comment]
This was implemented as a separated script that should be run before any reduction at Utah. If pixel shifts are detected, a new version of the affected raw frame with the pixel shifted back in place will be written (`lvm-e[imagetype]*` in the ancillary folder). Any reduction will check for the existence of `e` ancillary files, and reduce those instead of the original raw files.

Dmitry's report's will be implemented in a different branch.
